services:
  difficalcy-performanceplus:
    build:
      context: .
      target: difficalcy-performanceplus
    environment:
      - REDIS_CONFIGURATION=cache:6379
    volumes:
      - beatmaps:/app/beatmaps
    depends_on:
      - cache

  cache:
    image: redis:6

  docs:
    build: ./docs
    volumes:
      - ./docs:/docs

volumes:
  beatmaps:
